### ISSUE TITLE
Issue with Text To Speech feature on mobile

### ISSUE THREAD

**Issue by sbr464** [sbr464/meteor-notepad#1]
for some reason the TTS is not working on ios
I get this error anytime I click the Speak note button:

The ios app does not work in the ios simulator. It does work on my iphone though.

2015-03-03 20:28:36.009 meteor-notepad[503:92515] Uncaught Error: ReferenceError: Can't find variable: tts:2045:http://meteor.local/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb

**Comment by sbr464** [comment]
The photo and geolocation is working properly on the physical ios device.

The shake library cause the mobile build to take a about 30 seconds longer, but it does not hang up any more

**Comment by jazzdragon** [comment]
Cool, if it all works on the phone that's awesome. We should see tomorrow
if we can sync the phone and the computer in real time. We should probably
also tell the meteor guys about this bug.

**Comment by sbr464** [comment]
there are a few text to speech libraries if you want to try dropping in another one. 
http://plugins.cordova.io/#/search?search=speech

**Comment by sbr464** [comment]
there is an issue with the meteor.local url i believe. 

I deployed the app to http://peer64.meteor.com for testing

https://github.com/CollectionFS/Meteor-CollectionFS/issues/463 these guys are having the same issue with the meteor.local url and they had to hard code their public in the library or something. you may have to search for url pieces in the TTS library and swap a more public url
